version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: dummy_secret_key_base
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
